// Copyright (c) 2026 Hapbeat. MIT License.
#pragma once

#include "CoreMinimal.h"
#include "UObject/SoftObjectPtr.h"
#include "HapbeatEventEntry.generated.h"

// UHapbeatClip is referenced only via TSoftObjectPtr (a forward declaration is
// sufficient here). The full definition is included in HapbeatEventEntry.cpp
// where the pointer is dereferenced.
class UHapbeatClip;

/**
 * Haptic event mode. Determines how a trigger fires the event.
 * Mirrors Hapbeat.HapticMode (Unity SDK) — both modes are kept for wire parity.
 */
UENUM(BlueprintType)
enum class EHapticMode : uint8
{
	/** Send the event id as a PLAY command; the device resolves the clip locally from the installed Kit. */
	Command UMETA(DisplayName = "Command"),
	/**
	 * Stream a UHapbeatClip over UDP as PCM16. No Kit needed on the device.
	 * Dynamic gain / pan modulation is supported through the stream playback
	 * handle (see Phase 3).
	 */
	StreamClip UMETA(DisplayName = "Stream Clip"),
};

/**
 * A single haptic event definition within a UHapbeatEventMap.
 *
 * Supports two modes: Command (event id, device-resolved clip) and StreamClip
 * (a UHapbeatClip streamed over UDP). Triggers reference an entry by its stable
 * GUID (<see cref="Id"/>), never by list index, so reordering / inserting /
 * duplicating entries cannot silently break existing trigger wiring.
 *
 * Field set + getter logic mirror Hapbeat.HapbeatEventEntry (Unity SDK) verbatim.
 */
USTRUCT(BlueprintType)
struct HAPBEATSDK_API FHapbeatEventEntry
{
	GENERATED_BODY()

	// ---- Stable identifier ----
	//
	// Generated by the owning UHapbeatEventMap (PostEditChangeProperty) so that
	// add / duplicate operations always yield a unique, non-zero Id. Do NOT
	// generate inside the struct constructor: structs in TArray are value-
	// initialized frequently (resize / reallocation), which would either churn
	// Ids or assign duplicates. VisibleAnywhere = shown but not user-editable.
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Hapbeat",
		meta = (Tooltip = "Stable GUID identifying this entry across reorders and reloads. Assigned automatically; triggers reference it instead of the list index."))
	FGuid Id;

	// ---- Mode ----

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "How this event triggers haptic feedback.\nCommand: send the event id; the device plays its local clip.\nStreamClip: stream a UHapbeatClip over UDP."))
	EHapticMode Mode = EHapticMode::Command;

	// ---- Event ID (Command mode) ----

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Human-readable label for this event (e.g. \"Landing Impact\")."))
	FString DisplayName;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Event id left segment (the Kit name). See hapbeat-contracts event-id spec."))
	FString Category;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Event id right segment (the clip file name without extension)."))
	FString EventName;

	// ---- Gain ----

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Gain multiplier (0.0 to 2.0).", UIMin = "0.0", UIMax = "2.0", ClampMin = "0.0", ClampMax = "2.0"))
	float Gain = 1.0f;

	// ---- Targeting ----

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Target filter for device addressing. Empty = broadcast to all.\nExamples: player_1, */pos_neck, player_1/pos_chest"))
	FString Target;

	// ---- StreamClip mode ----

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Loop playback. Re-streams the clip continuously until Stop() is called.\nUsed for sustained / hold-style effects (drag, scrape, charge). Default off (one-shot)."))
	bool bLoop = false;

	// ---- Latency offset ----

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Per-entry delay offset (seconds), added to the global HapticDelaySeconds.\nPositive: fire later than global. Negative: fire earlier (the sum is clamped to >= 0).",
			UIMin = "-0.2", UIMax = "0.2", ClampMin = "-0.2", ClampMax = "0.2"))
	float DelayOffsetSeconds = 0.0f;

	// ---- Notes ----

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Designer notes (not sent to devices).", MultiLine = "true"))
	FString Notes;

	// ---- StreamClip asset ----

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Hapbeat",
		meta = (Tooltip = "Clip streamed over UDP as PCM16 (StreamClip mode only)."))
	TSoftObjectPtr<UHapbeatClip> StreamClip;

	// ---- Manifest intensity cache ----
	//
	// Studio authors parameters.intensity per Kit event in manifest.json. The
	// device is a pure executor (plays req.gain verbatim and never reads the
	// manifest), so the SDK must pre-multiply gain × intensity before putting
	// it on the wire. The authored value is baked here by the editor module
	// (Phase 5 "Refresh Intensities") so the runtime — which doesn't ship the
	// manifest — still has access to it. -1 = "not yet resolved / no matching
	// manifest entry" (callers fall back to plain Gain). 0 is a valid authored
	// silence. VisibleAnywhere so the user does not hand-edit it casually.
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Hapbeat",
		meta = (Tooltip = "Authored intensity baked from the Kit manifest (editor 'Refresh Intensities'). -1 = unresolved (falls back to Gain). Do not edit by hand."))
	float CachedManifestIntensity = -1.0f;

	// ---- Pure helpers (mirror the Unity getter logic verbatim) ----

	/**
	 * Computed event id in <category>.<name> form (contracts-compliant). Only
	 * meaningful in Command mode. Returns "" when EventName is empty; returns
	 * EventName alone when Category is empty; otherwise "Category.EventName".
	 */
	FString GetEventId() const
	{
		if (EventName.IsEmpty())
		{
			return FString();
		}
		if (Category.IsEmpty())
		{
			return EventName;
		}
		return Category + TEXT(".") + EventName;
	}

	/**
	 * Effective gain to send over the wire: Gain × CachedManifestIntensity.
	 * Applies to both Command and StreamClip modes (the device only honours
	 * req.gain). When the cache is unresolved (CachedManifestIntensity < 0)
	 * returns plain Gain; an authored intensity of exactly 0 is honoured (0 is
	 * a valid silence, so only the strictly-negative sentinel falls back).
	 */
	float GetEffectiveGain() const
	{
		return CachedManifestIntensity < 0.0f
			? Gain
			: Gain * CachedManifestIntensity;
	}

	/** True once Id has been assigned (a fresh value-initialized FGuid is all-zero / invalid). */
	bool HasValidId() const { return Id.IsValid(); }

	/** Whether this entry uses a path-based target (vs broadcast). */
	bool HasTarget() const { return !Target.IsEmpty(); }

	/**
	 * Standard body positions defined by the hapbeat-contracts device-addressing
	 * spec (the 12 pos_* vocabulary values, in spec order).
	 */
	static TArray<FString> StandardPositions();
};
